POST  http://localhost:3000/events
Content-Type: application/json

{
  "title":2,
  "details":"um evento para quem gosta de frio",
  "maximumAttendees":5
}

###

POST  http://localhost:3000/events/0e3905ec-9bac-42ab-9e0b-f4413cc754f9/attendees
Content-Type: application/json

{
  "name":"usuario teste 2",
  "email":"teste@hotmail.com"
}

###

GET   http://localhost:3000/events/0e3905ec-9bac-42ab-9e0b-f4413cc754f9


###

GET   http://localhost:3000/attendees/8/badge
###


GET   http://localhost:3000/attendees/8/check-in


###

GET   http://localhost:3000/events/0e3905ec-9bac-42ab-9e0b-f4413cc754f9/attendees?pageIndex=0