POST  http://localhost:3000/events
Content-Type: application/json

{
  "title":"summd",
  "details":"um evento para quem gosta de frio",
  "maximumAttendees":1
}

###

POST  http://localhost:3000/events/26fb56f8-c96f-4b54-b22f-e7a20389a835/attendees
Content-Type: application/json

{
  "name":"felipe",
  "email":"felipelkjl@hotmail.com"
}

###

GET   http://localhost:3000/events/c1ff5a3b-8c98-4b10-97ce-4f288d28e19c


###

GET   http://localhost:3000/attendees/2/badge
